#
# Note: dependencies are based on kotlin version
#
[versions]
# Core
androidGradlePlugin = '7.4.2'
kotlin = '1.7.10'
coreKtx = '1.9.0'
composeBom = '2022.12.00'
composeCompiler = '1.3.1'
lifecycleRuntimeKtx = '2.5.1'
activityCompose = '1.5.1'
navigationCompose = '2.5.3'
accompanist = '0.28.0'
# Tests
junit = '4.13.2'
androidJunit = '1.1.5'
espresso = '3.5.1'
# Lint
composeLintChecks = '1.1.1'

[libraries]
## Core ktx library
androidx-core-ktx = { group = 'androidx.core', name = 'core-ktx', version.ref = 'coreKtx' }
## Lifecycle
androidx-lifecycle-runtime-ktx = { group = 'androidx.lifecycle', name = 'lifecycle-runtime-ktx', version.ref = 'lifecycleRuntimeKtx' }
## Core library from BOM
androidx-compose-bom = { group = 'androidx.compose', name = 'compose-bom', version.ref = 'composeBom' }
androidx-compose-material = { group = 'androidx.compose.material', name = 'material' }
androidx-compose-material-icons-extended = { group = 'androidx.compose.material', name = 'material-icons-extended' }
androidx-compose-ui-tooling-preview = { group = 'androidx.compose.ui', name = 'ui-tooling-preview' }
## Compose integration with Activity
androidx-activity-compose = { group = 'androidx.activity', name = 'activity-compose', version.ref = 'activityCompose' }
## Compose integration with Navigation
androidx-navigation-compose = { group = 'androidx.navigation', name = 'navigation-compose', version.ref = 'navigationCompose' }
## Permissions
google-accompanist-permission = { group = 'com.google.accompanist', name = 'accompanist-permissions', version.ref = 'accompanist' }

# Tests
junit-junit = { group = 'junit', name = 'junit', version.ref = 'junit' }
androidx-junit = { group = 'androidx.test.ext', name = 'junit', version.ref = 'androidJunit' }
androidx-espresso = { group = 'androidx.test.espresso', name = 'espresso-core', version.ref = 'espresso' }

# Lint
slack-compose-lint = { group = 'com.slack.lint.compose', name = 'compose-lint-checks', version.ref = 'composeLintChecks' }

[plugins]
android-application = { id = 'com.android.application', version.ref = 'androidGradlePlugin' }
android-library = { id = 'com.android.library', version.ref = 'androidGradlePlugin' }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }